name: rowsandcolumns
description: Display a matrix made of rows and columns

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# Updated version as I try to integrate with central Github store
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # File names below were taken from the debugprint in Second.dart as it fills the matrixList
  # - don't actually have any green images, so I copied the blue ones & remamed the copies
  assets:
    - images/herdred.png      # Herd (>9 deer) 5 hrs (1,1)
    - images/smallred.png   # Small Group 5 hrs (1,2)
    - images/lonered.png      # Lone Deer 5 hrs (1,3)
    - images/stagred.png   # Lone Stag 5 hrs (1,4)
    - images/deerred.png   # Unknown 5 hrs (1,5)
    - images/outlinered.png   # Unconfirmed 5 hrs (1,6)
    - images/herdblue.png   # Herd (>9 deer) 12 hrs (2,1)
    - images/smallblue.png   # Small Group 12 hrs (2,2)
    - images/loneblue.png   # Lone Deer 12 hrs (2,3)
    - images/stagblue.png   # Lone Stag 12 hrs (2,4)
    - images/deerblue.png   # Unknown 12 hrs (2,5)
    - images/outlineblue.png   # Unconfirmed 12 hrs (2,6)
    - images/herdgreen.png   # Herd (>9 deer) 1.0 days (3,1)
    - images/smallgreen.png   # Small Group 1.0 days (3,2)
    - images/lonegreen.png   # Lone Deer 1.0 days (3,3)
    - images/staggreen.png   # Lone Stag 1.0 days (3,4)
    - images/deergreen.png   # Unknown 1.0 days (3,5)
    - images/outlinegreen.png   # Unconfirmed 1.0 days (3,6)
    - images/herdbrown.png   # Herd (>9 deer) 2.0 days (4,1)
    - images/smallbrown.png   # Small Group 2.0 days (4,2)
    - images/lonebrown.png   # Lone Deer 2.0 days (4,3)
    - images/stagbrown.png   # Lone Stag 2.0 days (4,4)
    - images/deerbrown.png   # Unknown 2.0 days (4,5)         copied deergrey
    - images/outlinebrown.png   # Unconfirmed 2.0 days (4,6)
    - images/herdgrey.png   # Herd (>9 deer) 5.0 days (5,1)
    - images/smallgrey.png   # Small Group 5.0 days (5,2)
    - images/lonegrey.png   # Lone Deer 5.0 days (5,3)
    - images/staggrey.png   # Lone Stag 5.0 days (5,4)
    - images/deergrey.png   # Unknown 5.0 days (5,5)
    - images/outlinegrey.png   # Unconfirmed 5.0 days (5,6)     -
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
